- id: unexport
  name: unexport
  description:
    "unexport is a linter that tries to keep the __all __ in your Python modules always up
    to date."
  entry: unexport
  language: python
  language_version: python3
  types: [python]
